### ISSUE TITLE
trafoOptPath silently drops error msg, exec time

### ISSUE THREAD

**Issue by MasonGallo** [berndbischl/ParamHelpers#120]
When calling `trafoOptPath` on a tune result, error.msg and exec.time are silently dropped. Looks like this is due to the default arguments for `OptPathDF`. Perhaps this should be added as an argument in case the user wants to keep these?

**Comment by jakob-r** [comment]
The problem is, that this function is only meant to be for the essential bits of the OptPath. We could of course add further arguments but then the code will get a bit lengthly because of the structure of the OptPath (if we want to limit ourselfs to the legit getters and setters available)
In your case I would recommend to just copy the columns of interest out of the untransformed OptPath, after calling `as.data.frame(opt.path)`.

@berndbischl: Tell me your thoughts.

**Comment by berndbischl** [comment]
@jakob-r 
no, IMHO this a totally direct bug. i have also already fixed it. you can be my boss and review it later :)
