### ISSUE TITLE
subsetParamSet

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/ParamHelpers#39]
have a function `getParamSubset` next to `dropParams`

**Comment by berndbischl** [comment]
name = subsetParamSet maye. Or just "subset".

**Comment by berndbischl** [comment]
maybe we should just add an argument "ids" to filterParams?

**Comment by kerschke** [comment]
Do I get it right, that we just want an argument which can be used to filter the parameter set based on the *name* of the parameter? And you suggested to call that argument `ids`?
If that's right, I'm not sure if I like the name `ids` as that somehow suggests integer, whereas a name is more likely a character. Since parameter names might also be very long, I actually like the idea of having integer values as well. So, how about adding an integer argument `ids` and a name argument (e.g. `subset`)?

**Comment by berndbischl** [comment]
> Do I get it right, that we just want an argument which can be used to filter the parameter set based on 
> the name of the parameter? 

Yes. 

Note that we use the "ids" all over the place with strings? also in learner, task, etc?  and the name of a param is called indeed "id". So use id for the name. Subsetting by position is much more error-prone. But if you really want to, you can allow position ints for "ids" as well.

**Comment by kerschke** [comment]
Ok, I see your point in calling it "ids". I have to admit, I was not thinking of that naming convention in mlr when writing that down.
Anyways, this issue should be solved with my current pull request. Thus, in case you're happy with that new version, you may close this issue ;-)

**Comment by berndbischl** [comment]
> I was not thinking of that naming convention in mlr when writing that down.

Actually it doesnt really matter, just a side remark. The relevant point is that that the param name slot is indeed called "id" in PH.
