### ISSUE TITLE
filter to only the tunable params

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/ParamHelpers#42]
@kerschke 

Add an arg to filterParams to do exactly that? that is what we want right?

**Comment by kerschke** [comment]
So, you're thinking of something like this?

```{r}
filterParams = function(par.set, type, tunable = c(TRUE, FALSE)) {
  assertSubset(type, c("numeric", "integer", "numericvector", "integervector", "discrete",
    "discretevector", "logical", "logicalvector", "function", "untyped"))
  assertLogical(tunable, min.len = 0L, max.len = 2L, unique = TRUE)
  if (!is.null(par.set$forbidden))
    stopf("Operation not allowed for param set with forbidden region currently!")
  par.set$pars = Filter(function(p) p$type %in% type, par.set$pars)
  par.set$pars = Filter(function(p) p$tunable %in% tunable, par.set$pars)
  return(par.set)
}
```

I was thinking of making `tunable = c(TRUE, FALSE)` the default, because this way, we don't break *old* code. If you run your code again, the `tunable`-flag will automatically be set (without influencing any of your results), so I suggest filtering should not remove any parameters based on that `tunable`-flag as well. Do you agree?
And should we have some sort of short-cut for considering all types, e.g. `type = NULL` or `type = "all"`. This way, it's more comfortable to just filter based on the `tunable`-argument, e.g. `filterParams(ps, NULL, TRUE)`.

**Comment by berndbischl** [comment]
>So, you're thinking of something like this?

Yes I guess. 

> I was thinking of making tunable = c(TRUE, FALSE) the default

Sure. The default is  NOT to filter on that flag. 

> And should we have some sort of short-cut for considering all types, e.g. type = NULL or type = "all". 

Yes. NULL is best right and "consistent" as we often use it as "argument not there"?

**Comment by berndbischl** [comment]
@kerschke 
Thx: I see no reason to allow tunable = logical(0) in the filter, that always returns nothing. 
(Note: you allowed this but did not document it....)
So I removed this.

Would you be so nice to take over #39, by adding, if you agree, "ids" to filterParams?

And close here or?
